infinitybase/bako-safe-ui

- src/modules/transactions/components/TransactionCard/Details.tsx
- src/modules/transactions/components/TransactionCard/DetailsDialog.tsx
- src/modules/transactions/components/TransactionCard/DetailsTransactionStepper.tsx
- src/modules/vault/pages/details/index.tsx
https://app.clickup.com/t/86a3cqber
- Concluída.
> FIX: Organize transaction requests

- src/modules/vault/hooks/create/useCreateVault.ts
- src/modules/vault/hooks/create/useCreateVaultDialog.ts
https://app.clickup.com/t/86a3cp0at
> FIX(VAULT): Reset all form states when create a vault

- src/modules/transactions/components/TransactionCard/Details.tsx
- src/modules/transactions/components/TransactionCard/DetailsDialog.tsx
https://app.clickup.com/t/86a3ge8t8
> FIX: Added scroll to transaction card in mobile

- src/components/autocomplete/index.tsx
- src/modules/transactions/components/dialog/create/transactions.tsx
- src/modules/vault/components/dialog/create/form/steps/addresses.tsx
- src/modules/vault/hooks/create/useCreateVaultDialog.ts
https://app.clickup.com/t/86a3ge0c0
> FIX: Create Vault Modal options

- src/modules/settings/hooks/useSettings.ts
https://app.clickup.com/t/86a376vgu
> CHORE: Dont open settings on first login

- src/layouts/dashboard/content.tsx
- src/themes/default.ts
https://app.clickup.com/t/86a3jmadn
> fix(drawers): drawers no longer interferes with the background

- src/modules/transactions/components/TransactionCard/VaultInfo.tsx
https://app.clickup.com/t/86a3kcbbp
> FIX: Transaction Card - Reduced space between icon and wk name

- src/components/select/index.tsx
- src/modules/vault/components/dialog/create/form/steps/addresses.tsx
https://app.clickup.com/t/86a3j37xh
> FIX: Set template - When select a template, remove the current addresses and use only the template

- src/modules/settings/components/drawer/index.tsx
- src/modules/vault/components/drawer/index.tsx
- src/modules/workspace/components/settings/drawer.tsx
https://app.clickup.com/t/86a3kd4x6
> fix(drawers): removes transparency from drawer backgrounds

- src/modules/addressBook/pages/addressBook/index.tsx
- src/modules/home/pages/home.tsx
- src/modules/notifications/components/drawer/index.tsx
- src/modules/notifications/components/emptyState/index.tsx
- src/modules/transactions/pages/user-transactions/index.tsx
- src/modules/vault/components/CardDetails.tsx
- src/modules/vault/pages/details/index.tsx
- src/modules/vault/pages/user-vaults/index.tsx
https://app.clickup.com/t/86a3jfeea
> Fix/adjusts UI mobile dev net

- src/modules/transactions/components/dialog/create/transactions.tsx
- src/modules/vault/components/dialog/create/form/steps/addresses.tsx
- Aguardando confirmação do Henrique sobre também bloquear a criação de vault, caso haja  10 endereços
- Concluído: https://app.clickup.com/t/86a3kva2v
> FIX: Disabled add more address in create vault if it has 10 address

- src/components/autocomplete/index.tsx
- src/components/dialog/modal.tsx
- src/modules/addressBook/hooks/useAddressBook.tsx
- src/modules/addressBook/hooks/useAddressBookAutocompleteOptions.ts
- src/modules/transactions/components/dialog/create/accordion/item.tsx
- src/modules/transactions/components/dialog/create/transactions.tsx
- src/modules/transactions/hooks/create/useCreateTransaction.ts
- src/modules/transactions/hooks/create/useCreateTransactionForm.ts
- src/modules/vault/components/dialog/create/form/steps/addresses.tsx
- src/modules/vault/components/dialog/create/index.tsx
- src/modules/vault/states/useVaultState.ts
- src/modules/workspace/components/form/CreateMembersForm.tsx
- src/modules/workspace/hooks/members/useChangeMember.ts
- src/modules/workspace/hooks/members/useChangeMemberForm.ts
- src/utils/keep-options-near-to-container.ts
https://app.clickup.com/t/86a3kvac1
> FIX: Added infinity scroll to create transaction and add member

- src/modules/transactions/components/dialog/create/accordion/actions.tsx
- src/modules/transactions/components/dialog/create/form.tsx
- src/modules/transactions/components/dialog/create/index.tsx
- src/modules/transactions/components/dialog/create/transactions.tsx
- src/modules/transactions/hooks/create/useCreateTransaction.ts
https://app.clickup.com/t/86a3mvu3e
> FIX: Create Transaction Confirm Button

- src/modules/vault/components/dialog/create/form/steps/info.tsx
https://app.clickup.com/t/86a3ky369
> FIX: Keep name state/value when change step on create vault

- pnpm-lock.yaml
- src/modules/dapp/pages/VaultConnector.tsx
https://app.clickup.com/t/86a3hb8ht
> FIX:DAPP -  Added dynamic height to vault connector

- pnpm-lock.yaml
- src/modules/vault/components/CardDetails.tsx
https://app.clickup.com/t/86a3kxx06
> FIX: Changed empty assets text

- src/modules/auth/hooks/useSignIn.ts
- src/utils/constants.ts
https://app.clickup.com/t/86a3nanck
> chore(connection): added a validation to beta 5 network

- src/layouts/dashboard/header.tsx
- src/modules/workspace/components/create/index.tsx
- src/modules/workspace/hooks/create/useCreateWorkspace.ts
https://app.clickup.com/t/86a3kxkp9
> CHORE: Create workspace modal cancel button now goes back one step when click on cancel

- src/modules/settings/components/drawer/index.tsx
- Em andamento, pr aberta para testar no celular com link de preview
- Feito: https://app.clickup.com/t/86a3n0hmj
> CHORE: Add validation to settings when the account is webauth

- src/modules/addressBook/hooks/useAddressBookAutocompleteOptions.ts
- src/modules/template/components/dialog/steps/AddressStep.tsx
- src/modules/transactions/components/dialog/create/transactions.tsx
- src/modules/vault/components/dialog/create/form/steps/addresses.tsx
- src/modules/workspace/components/form/CreateMembersForm.tsx
https://app.clickup.com/t/86a3q5k30
> FIX - Can select the same address multiple times when creating a tx

- src/modules/transactions/components/dialog/create/form.tsx
- src/modules/transactions/components/dialog/create/index.tsx
- src/modules/transactions/components/dialog/create/transactions.tsx
- src/modules/transactions/hooks/create/useCreateTransaction.ts
https://app.clickup.com/t/86a3quqag
> FIX: Transaction - Changed some fee names and added a calc to show balance - reserved amount

- src/modules/vault/pages/details/index.tsx
https://app.clickup.com/t/86a3qpy2q
> CHORE: Hide set template button

- .env.example
- .env.preview
- .env.production
- Increases the expiration time of cookies to be greater than the expiration time of the auth token
https://app.clickup.com/t/86a3rbw7r
> chore(env): expiration time of cookies is longer than expiration time of the authentication token

- src/modules/addressBook/hooks/useAddressBook.tsx
https://app.clickup.com/t/86a3t4g68
> FIX:Addressbook - added the correct query to refetch

- src/components/dialog/modal.tsx
- src/components/select/index.tsx
- src/modules/addressBook/hooks/useInfiniteListContactsRequest.ts
- src/modules/addressBook/services/methods.ts
- src/modules/vault/components/dialog/create/form/steps/addresses.tsx
- src/modules/vault/components/dialog/create/index.tsx
- src/themes/default.ts
Em andamento.
- Corrigido endereços não estavam sendo mostrados após o quinto input
-  O select com a quantidade de assinates do vault abre para cima, caso tenha 2 ou mais endereços registrados
Concluída. Scroll será ajustado depois
> FIX: Create vault form improviments

- src/layouts/dapp/container.tsx
https://app.clickup.com/t/86a3tmcvg
> CHORE: added dark background to connector

- src/App.tsx
- src/modules/auth/hooks/useAuth.ts
- The user is only logged out when they change or create an account in the wallet they used to log in
https://app.clickup.com/t/86a3nz2h2
> fix(auth): user is only logged out when changing or creating an account in wallet they used to login

- src/modules/addressBook/hooks/useContactToast.tsx
- src/modules/auth/hooks/useWebAuthn.ts
- src/modules/notification/hooks/useNotification.tsx
PR opened to validate changes on phone
- Done
> CHORE: Login flow

- src/layouts/dashboard/sidebar.tsx
- src/modules/notifications/components/emptyState/index.tsx
- src/modules/notifications/hooks/useAppNotifications.ts
- src/modules/notifications/hooks/useListNotificationsRequest.ts
- src/modules/notifications/store/useNotificationsStore.ts
- src/modules/transactions/providers/send/provider.tsx
- src/modules/vault/components/box/index.tsx
- src/modules/vault/components/drawer/hook.ts
- src/modules/vault/components/drawer/index.tsx
- src/modules/vault/hooks/assets/useVaultAssets.ts
- src/modules/vault/hooks/useVaultListRequest.ts
Notifications reloading is working fine in local. 
Pr opened to verify if works in preview link as well
DONE: https://app.clickup.com/t/86a3qpqpc
> FIX: Loading Improviments v2

- src/layouts/dashboard/sidebar.tsx
- src/main.tsx
- src/modules/transactions/hooks/create/useCreateTransaction.ts
- src/modules/transactions/services/methods.ts
- src/modules/vault/components/CardDetails.tsx
- src/modules/vault/components/SettingsOverview.tsx
- src/modules/vault/components/box/index.tsx
> CHORE: Added validation to create transaction button based on reserved amount and max fee

- src/components/dialog/modal.tsx
- src/modules/vault/components/dialog/create/form/steps/addresses.tsx
- src/modules/vault/components/dialog/create/index.tsx
- src/themes/default.ts
PR opened to ask for someone to test
Done: https://app.clickup.com/t/86a3tqbz3
> FIX: Create vault form - IOS Scroll

- src/modules/transactions/pages/list/index.tsx
- src/modules/vault/pages/settings/index.tsx
https://app.clickup.com/t/86a3vbmcr
> fix(vault): adjust vaults link

- src/modules/home/components/HomeTransactions/index.tsx
- src/modules/transactions/components/TransactionCard/Details.tsx
https://app.clickup.com/t/86a403a78
> FIX: Home Transaction List Empty State

- src/App.tsx
- src/modules/assets-tokens/hooks/useTxAmountToUSD.ts
- src/modules/assets-tokens/store/index.ts
- src/modules/assets-tokens/store/useTokensStore.ts
- src/modules/core/utils/assets/address.ts
- src/modules/core/utils/assets/data.ts
- src/modules/home/hooks/useTokensUSDAmountRequest.ts
- src/modules/home/services/methods.ts
- src/modules/transactions/components/TransactionCard/Amount.tsx
- src/modules/transactions/components/TransactionCard/Details.tsx
https://app.clickup.com/t/86a40vkcq
> FEAT: Add dynamic usd value to tx amount card

- src/modules/home/components/HomeTransactions/index.tsx
- src/modules/workspace/components/wkHomeTransactions/index.tsx
- src/modules/workspace/pages/home/index.tsx
https://app.clickup.com/t/86a404w79
> FIX: Home/Wk Transaction type filters 

- src/App.tsx
- src/modules/assets-tokens/hooks/useTxAmountToUSD.ts
- src/modules/assets-tokens/store/useTokensStore.ts
- src/modules/home/pages/home.tsx
- src/modules/transactions/components/TransactionCard/Amount.tsx
Concluído!
https://app.clickup.com/t/86a41crut
> FIX: Tx Usd Amount on first render

- src/modules/addressBook/components/contactCard/index.tsx
- src/modules/vault/components/CardDetails.tsx
- src/modules/vault/components/VaultCard.tsx
https://app.clickup.com/t/86a3y11hr
Aguardando validação
> CHORE: Change cards backgrounds

- src/modules/dapp/components/transaction/from-to.tsx
https://app.clickup.com/t/86a3t7524
> CHORE:Dapp - Change fuel address to raw address

- src/modules/transactions/components/TransactionCard/DepositDetails.tsx
- src/modules/transactions/components/TransactionCard/TransactionStepper.tsx
- src/modules/transactions/components/TransactionCard/deposit-details/DetailItem.tsx
https://app.clickup.com/t/86a41zq75
> FIX: Added "from" address to deposit card and some align adjustments

- src/modules/addressBook/hooks/useAddressBook.tsx
https://app.clickup.com/t/86a3trka7
> FIX: Added auto refresh/reloag to workspace add member form

- src/modules/transactions/components/TransactionCard/Container.tsx
- src/modules/transactions/components/TransactionCard/Details.tsx
https://app.clickup.com/t/86a42xvjz
> CHORE: CLI TX CARD

- src/modules/core/models/notification.ts
- src/modules/notifications/hooks/useAppNotifications.ts
https://app.clickup.com/t/86a3w24b0
> FIX: Notifications redirect 

- src/modules/vault/components/ExtraVaulCard.tsx
- src/modules/workspace/components/create/index.tsx
- src/modules/workspace/hooks/create/useCreateWorkspace.ts
https://app.clickup.com/t/86a3vhf36
> FIX: Select workspace dialog opening when create a new wk

- src/modules/transactions/hooks/list/useTransactionList.ts
- src/modules/transactions/hooks/signature/useSignTransaction.ts
- src/modules/transactions/providers/send/provider.tsx
- src/modules/transactions/utils.ts
it is working on local. 
Now gonna be testing in preview.
Added another validation for "not enough coins" error. 
Approved: https://app.clickup.com/t/86a40un6d
> FIX: Transactions infinite loading

- src/modules/settings/components/drawer/index.tsx
https://app.clickup.com/t/86a41ha82
> CHORE: Added name length validation to name input on settings

- .env.example
- .env.preview
- .env.production
- src/config/cookies.ts
- Removes cookie expiration time
https://app.clickup.com/t/86a41hxnq
> fix(auth): removes cookies expiration time

- src/modules/workspace/hooks/members/useChangeMember.ts
- Adjusts the logic of requests made to add members to the workspace
https://app.clickup.com/t/86a45fpvu
> fix(workspace): shows edit button only when member data is loaded

- src/modules/auth/components/connector.tsx
- src/modules/auth/hooks/useDrawerWebAuthn.ts
- src/modules/auth/hooks/useSignIn.ts
- src/modules/auth/pages/signin.tsx
https://app.clickup.com/t/86a4a6vct
> FIX: Sigin in one try

- src/modules/auth/hooks/useAuth.ts
- src/modules/auth/hooks/useSignIn.ts
- src/modules/transactions/components/TransactionCard/Details.tsx
- src/modules/transactions/components/TransactionCard/deposit-details/DetailItem.tsx
- src/modules/vault/components/dialog/create/form/steps/addresses.tsx
- src/modules/vault/hooks/create/useCreateVault.ts
- src/modules/workspace/components/dialog/select.tsx
Depends on https://github.com/infinitybase/bako-safe-api/pull/201
> Convert bech32 addresses to b256

- src/modules/workspace/hooks/members/useChangeMember.ts
https://app.clickup.com/t/86a4htm92
- Also, invalidate workspace request when delete a member.
> FIX: Workspace add member

- src/modules/workspace/components/settings/drawer.tsx
https://app.clickup.com/t/86a4htk6r
> fix(workspace): adjusts workspace vault count

- src/components/bakoLoading/index.tsx
- src/modules/core/hooks/useGetParams.tsx
- src/modules/home/components/HomeTransactions/index.tsx
- src/modules/notifications/hooks/useAppNotifications.ts
- src/modules/notifications/hooks/useListNotificationsRequest.ts
- src/modules/settings/hooks/useMySettingsRequest.ts
- src/modules/transactions/pages/user-transactions/index.tsx
- src/modules/vault/components/drawer/hook.ts
- src/modules/vault/hooks/assets/useVaultAssets.ts
- src/modules/vault/hooks/details/useVaultDetails.ts
- src/modules/vault/pages/details/index.tsx
- src/modules/workspace/components/wkHomeTransactions/index.tsx
- src/modules/workspace/hooks/details/useWorkspaceDetails.ts
- src/modules/workspace/hooks/useUserWorkspacesRequest.ts
- src/modules/workspace/hooks/useWorkspace.tsx
- src/modules/workspace/pages/balance/index.tsx
- src/modules/workspace/pages/home/index.tsx
https://app.clickup.com/t/86a4hwpca
> FIX: Workspace context loadings

- index.html
- src/themes/default.ts
https://app.clickup.com/t/86a4jvht3
> CHORE: Add default background color to HTML

- src/config/api.ts
- Just removing the cookies when the token expires is enough to redirect the user to login
https://app.clickup.com/t/86a4j33bj
> fix(auth): disconnects user when auth token is invalid

- src/modules/core/hooks/bakosafe/transaction.ts
- src/modules/transactions/components/TransactionCard/Status.tsx
- src/modules/transactions/hooks/send/useSendTransaction.ts
https://app.clickup.com/t/86a4hzpch
> FIX: Wrongly loading state in transactions card while signing

- src/modules/home/components/HomeTransactions/index.tsx
- src/modules/vault/components/dialog/create/form/steps/addresses.tsx
- src/modules/vault/components/dialog/create/index.tsx
- src/modules/workspace/components/wkHomeTransactions/index.tsx
https://app.clickup.com/t/86a41cq4b
> FIX: UI Adjustments in mobile

- src/modules/transactions/components/TransactionCard/DepositDetails.tsx
- src/modules/transactions/components/TransactionCard/deposit-details/DetailItem.tsx
https://app.clickup.com/t/86a4jzgmv
- the "@ts-ignore" in DepositDetails file, at line 15 is because the value sent by API is different from fuel-ts package. 
If needed, i can just create an new interface/type
> FIX: Depoist card from address

- src/modules/cli/hooks/APIToken/create/useCreateAPIToken.ts
- src/modules/cli/hooks/APIToken/list/useGetAPITokensRequest.ts
- src/modules/cli/hooks/useCLI.ts
- src/modules/transactions/components/TransactionCard/deposit-details/DepositDetails.tsx
- src/modules/transactions/pages/user-transactions/index.tsx
- src/modules/vault/components/SettingsOverview.tsx
- src/modules/vault/hooks/create/useCreateVault.ts
- src/modules/vault/hooks/details/useVaultDetails.ts
- src/modules/workspace/components/settings/drawer.tsx
- src/modules/workspace/hooks/details/useWorkspaceDetails.ts
- src/modules/workspace/hooks/members/useChangeMember.ts
- src/modules/workspace/hooks/useGetWorkspaceRequest.ts
- src/modules/workspace/hooks/useIsFilteringInProgress.ts
- src/modules/workspace/hooks/useIsWorkspaceReady.ts
- src/modules/workspace/hooks/useWorkspace.tsx
- src/modules/workspace/pages/home/index.tsx
- src/modules/workspace/pages/members/create/index.tsx
https://app.clickup.com/t/86a4jwdu4
> FIX: GIF Loading adjustments V2

- src/config/api.ts
- src/modules/auth/hooks/useAuth.ts
- src/modules/workspace/hooks/useWorkspace.tsx
https://app.clickup.com/t/86a4jwuh7
> FIX: User can see informations from another account

- src/App.tsx
- src/config/api.ts
https://app.clickup.com/t/86a4kkf4n
> fix(axios): disconnects user when receiving a response with status 401

- src/modules/home/hooks/useHomeTransactions.ts
- src/modules/home/hooks/useHomeTransationsRequest.ts
- src/modules/transactions/hooks/context/useTransactionDetails.ts
- src/modules/transactions/pages/user-transactions/index.tsx
- src/modules/transactions/services/types.ts
- src/modules/vault/components/drawer/hook.ts
- src/modules/vault/hooks/list/useVaultTransactionsList.ts
- src/modules/vault/hooks/list/useVaultTransactionsRequest.ts
- src/modules/vault/layout/sidebar.tsx
- src/modules/vault/pages/vault-transactions/index.tsx
- src/modules/workspace/hooks/details/useWorkspaceDetails.ts
- src/modules/workspace/hooks/useWorkspace.tsx
https://app.clickup.com/t/86a4jv8yc
> FIX: Reset filter when switch pages and adjust notification selected transaction

- src/components/commingSoonDialog/index.tsx
- src/components/icons/notify-icon.tsx
- src/modules/cli/hooks/CommingSoon/useCommingSoon.tsx
- Center icon
- Center text
- Adjust spacing between icon and title
- Closes modal and shows confirmation toast when you click the notify button
https://app.clickup.com/t/86a4gr446
> fix(cli): adjust coming soon icon position and text alignment

- src/modules/workspace/hooks/members/useChangeMember.ts
- src/modules/workspace/hooks/members/useChangeMemberForm.ts
https://app.clickup.com/t/86a4ka6pk
> FIX: Disable add member button when it has any validation error

- src/modules/auth/hooks/useSignIn.ts
- src/modules/auth/hooks/useWebAuthn.ts
https://jam.dev/c/dc8bbbec-ea23-402d-806b-d3daf893331b
Não foi feito uma task ainda, tem apenas o jam
> FIX: Add gif loading in webauthn login

- src/modules/vault/hooks/list/useVaultTransactionsRequest.ts
https://app.clickup.com/t/86a4k9r61
> FIX: Added a refetch interval to vault transactions list request

- src/modules/assets-tokens/hooks/useTxAmountToUSD.ts
- src/modules/core/hooks/bakosafe/transaction.ts
- src/modules/core/hooks/useGetTokenInfos.ts
- src/modules/dapp/services/fuel-transaction.ts
- src/modules/transactions/components/TransactionCard/AssetBoxInfo.tsx
- src/modules/transactions/components/TransactionCard/Container.tsx
- src/modules/transactions/components/TransactionCard/Details.tsx
- src/modules/transactions/components/TransactionCard/transfer-details/ConnectorInfos.tsx
- src/modules/transactions/components/TransactionCard/transfer-details/TransactionBreakdown.tsx
- src/modules/transactions/components/transactionCardMobile/index.tsx
- src/modules/transactions/hooks/context/useTransactionDetails.ts
- src/modules/transactions/hooks/details/index.ts
- src/modules/transactions/hooks/details/useVerifyTransactionInformations.ts
- src/modules/transactions/hooks/list/useGetPendingTransactionsList.ts
- src/modules/transactions/hooks/list/useTransactionList.ts
- src/modules/transactions/hooks/send/useSendTransaction.ts
- src/modules/transactions/hooks/signature/useSignTransaction.ts
- src/modules/transactions/providers/toast.tsx
- src/modules/workspace/hooks/useIsFilteringInProgress.ts
- src/modules/workspace/hooks/useIsWorkspaceReady.ts
- src/utils/current-path.ts
https://app.clickup.com/t/86a4kkhf5
> FIX: Connector/Dapp - Gif animatio and tx cards from connector

- package.json
depends on https://github.com/infinitybase/bako-safe/pull/58
> Update fuels ts to 0.94

- src/modules/cli/hooks/APIToken/list/useListAPITokens.ts
- src/modules/cli/hooks/APIToken/useAPIToken.ts
https://app.clickup.com/t/86a4m1q58
> FIX: Api tokens list missing

- src/components/autocomplete/index.tsx
- src/modules/transactions/components/dialog/create/transactions.tsx
- src/modules/vault/components/dialog/create/form/steps/addresses.tsx
- src/modules/workspace/hooks/members/useChangeMember.ts
https://app.clickup.com/t/86a4pb1du
> FIX: Added a contact as member

- src/modules/cli/hooks/useCLI.ts
- src/modules/vault/hooks/details/useVaultDetails.ts
- src/modules/vault/hooks/useVaultByIdRequest.ts
- src/modules/vault/services/methods.ts
https://app.clickup.com/t/86a4p2fwx
> FIX: Signers can't access vault

- src/modules/dapp/hooks/useTransactionSocket.ts
- src/modules/dapp/pages/transactionConfirm.tsx
https://app.clickup.com/t/86a4qa8r3
> FIX: DAPP/Connector - Connect socket in first try

- src/App.tsx
- src/modules/dapp/hooks/useTransactionSocket.ts
- src/modules/dapp/pages/transactionConfirm.tsx
- src/modules/workspace/WorkspaceProvider.tsx
- src/modules/workspace/hooks/details/useWorkspaceDetails.ts
- src/modules/workspace/hooks/useIsFilteringInProgress.ts
- src/modules/workspace/hooks/useIsWorkspaceReady.ts
https://app.clickup.com/t/86a4qa8r3
> FIX: Connector Focus V2

- src/modules/dapp/hooks/useTransactionSocket.ts
- src/modules/dapp/pages/transactionConfirm.tsx
- src/modules/dapp/services/fuel-transaction.ts
Complement of this task: https://app.clickup.com/t/86a4r7efn and this pr https://github.com/infinitybase/bako-safe-ui/pull/360
1. In the first task, only the issue with context/git animation was solved.
2. In this one, we fix the fee error `insuficient max fee amount` that was happening when the `summary.getTransactionSummary` was called. (Line 75 on `useTransactionSocket` file).
> FIX: Connector tx summary fee

- src/modules/auth/hooks/useAuth.ts
- Fixes redirection of the connector user when logging in
> fix(auth): add parameters to url when logging out connector user

- src/modules/vault/components/dialog/create/index.tsx
- src/modules/vault/hooks/create/useCreateVault.ts
- src/modules/vault/hooks/create/useCreateVaultDialog.ts
- src/modules/vault/hooks/create/useCreateVaultForm.ts
https://app.clickup.com/t/86a3xgakq
> FIX:Adjusts create vault form

- src/modules/transactions/components/TransactionCard/deposit-details/DetailItem.tsx
- src/modules/transactions/hooks/useGetAssetsByOperations.ts
- src/modules/transactions/services/types.ts
https://app.clickup.com/t/86a4v75b4
> FIX: Black screen when log in in staging

- src/modules/core/hooks/useScreenSize.ts
- src/modules/transactions/components/TransactionCard/Actions.tsx
- src/modules/transactions/components/TransactionCard/Amount.tsx
- src/modules/transactions/components/TransactionCard/AssetBoxInfo.tsx
- src/modules/transactions/components/TransactionCard/Container.tsx
- src/modules/transactions/components/TransactionCard/Details.tsx
- src/modules/transactions/components/TransactionCard/DetailsDialog.tsx
- src/modules/transactions/components/TransactionCard/DetailsTransactionStepper.tsx
- src/modules/transactions/components/TransactionCard/Status.tsx
- src/modules/transactions/components/TransactionCard/deposit-details/DetailItem.tsx
- src/modules/transactions/components/TransactionCard/transfer-details/TransactionBreakdown.tsx
- src/modules/transactions/components/TransactionCard/transfer-details/contract-call/ContractAddresses.tsx
- src/modules/transactions/components/TransactionCard/transfer-details/mint-token/MintToken.tsx
- src/modules/transactions/components/transactionCardMobile/index.tsx
- src/modules/transactions/hooks/details/useTransactionHistory.ts
- src/modules/transactions/hooks/details/useTransactionHistoryRequest.ts
- src/modules/transactions/hooks/details/useVerifyTransactionInformations.ts
- src/modules/transactions/hooks/send/useSendTransaction.ts
- src/modules/transactions/hooks/signature/useSignTransaction.ts
- src/modules/transactions/states/useTransactionState.ts
https://app.clickup.com/t/86a4wrgwg
https://app.clickup.com/t/86a4wu5py
Adjusts: Show tx details in mobile and avoid duplicated loadings in tx card.
Open in draft to share preview link
> FIX: Show tx details in mobile and avoid duplicated loading state in tx card

- src/modules/transactions/components/TransactionCard/Details.tsx
- src/modules/transactions/components/TransactionCard/DetailsTransactionStepper.tsx
- src/modules/transactions/components/TransactionCard/Status.tsx
- src/modules/transactions/hooks/details/useTransactionHistory.ts
- src/modules/transactions/hooks/details/useTransactionHistoryRequest.ts
- src/modules/transactions/hooks/signature/useSignTransaction.ts
https://app.clickup.com/t/86a4x2z21
https://app.clickup.com/t/86a4x2817
> FIX: Retry Button loading state and tx history

- src/modules/vault/hooks/create/useCreateVaultDialog.ts
- Removed origin validation to verify if the user is accessing by the dapp. Now we only verify it by the sessionId.
> FIX: Vault redirect validation

- src/modules/dapp/pages/VaultConnector.tsx
- Logout user when cancel vault selection
https://app.clickup.com/t/86a4xzyj8
> feat(connetor): logout user when cancel vault selection

- src/modules/workspace/hooks/useWorkspace.tsx
https://app.clickup.com/t/86a4z0620
> FIX: Use Navigate instead authenticate user in the workspace

- src/modules/core/utils/assets/data.ts
- Adds default value to unknown asset
https://app.clickup.com/t/86a5281xy
> fix(assets): add default values to unknown asset

- src/modules/vault/components/dialog/create/form/steps/addresses.tsx
- src/modules/vault/hooks/create/useCreateVault.ts
- src/modules/vault/hooks/create/useValidateAddress.ts
- Revalidate address if user insert the same address in the same input
https://app.clickup.com/t/86a51tknt
> fix(vault): revalidate address if user insert the same address in the same input

- src/modules/core/hooks/bakosafe/sendTransaction.ts
- src/modules/core/hooks/bakosafe/transaction.ts
- src/modules/transactions/components/TransactionCard/Actions.tsx
- src/modules/transactions/components/TransactionCard/DetailsDialog.tsx
- src/modules/transactions/components/dialog/create/index.tsx
- src/modules/transactions/hooks/create/useCreateTransaction.ts
- src/modules/transactions/hooks/signature/useSignTransaction.ts
- src/modules/transactions/services/methods.ts
- Need to solve the problem when use the button `Create And Sign`: The toast and the loading is freezing in the send state
> FIX: Adjust Create-and-sign tx button and decline button

- src/modules/transactions/hooks/context/useTransactionDetails.ts
- src/modules/vault/components/modal/hook.ts
- src/modules/vault/components/modal/index.tsx
https://app.clickup.com/t/86a50tdur
> FIX: Remove notification transaction filter when users changes pages or leaves the vault

- src/modules/vault/components/modal/index.tsx
https://app.clickup.com/t/86a52h4fw
> FIX: Adjust create vault modal scroll from vault home

- src/modules/addressBook/components/form/index.tsx
- src/modules/cli/components/APIToken/create/form.tsx
- src/modules/settings/components/drawer/index.tsx
- src/modules/transactions/components/dialog/create/form.tsx
- src/modules/vault/components/dialog/create/form/steps/info.tsx
https://app.clickup.com/t/86a51nmfz
> CHORE: Add max length to some inputs

- src/App.tsx
- src/layouts/dashboard/header.tsx
- src/modules/auth/hooks/useAuth.ts
- src/modules/auth/services/methods.ts
- src/modules/core/hooks/fuel/useListConnectors.ts
- src/modules/core/hooks/fuel/useWallet.ts
https://app.clickup.com/t/86a50v71q
> fix: logout with fuelet and webAuthn

- src/modules/home/hooks/useTokensUSDAmountRequest.ts
Local Working Great, gonna be test in preview link
> FIX: Token Query - USD Amount

- src/modules/auth/hooks/useAuth.ts
- src/modules/transactions/hooks/context/useTransactionDetails.ts
- src/modules/transactions/hooks/list/useGetPendingTransactionsList.ts
https://app.clickup.com/t/86a52h9qf
> FIX: Add vault tx list to pending tx list

- src/modules/auth/hooks/signIn/useDappSignIn.ts
- src/modules/auth/hooks/signIn/useWalletSignIn.ts
- src/modules/auth/hooks/signIn/useWebSignIn.ts
- User is redirected correctly after logging in
> fix(auth): user is now redirect correctly after login

- src/layouts/dashboard/header.tsx
- src/modules/network/components/dialog/index.tsx
- src/modules/network/hooks/useNetworks.ts
- Disable button on network dialog if url is invalid
- Clear form after closing modal
> fix: network switch

- src/modules/transactions/components/TransactionCard/Amount.tsx
- src/modules/transactions/components/TransactionCard/AssetBoxInfo.tsx
- src/modules/transactions/components/TransactionCard/deposit-details/TokenInfos.tsx
https://app.clickup.com/t/86a52c3vy
> FIX: Transaction card assets size

- src/modules/vault/components/SettingsSigners.tsx
https://app.clickup.com/t/86a559t5p
> FIX: Vault settings required signers count

- src/modules/auth/components/header.tsx
- src/modules/auth/components/webAuthn/form.tsx
https://app.clickup.com/t/86a54wqkf
> CHORE: Add subtitle and description text in the sigin page

- src/modules/termsOfUse/utils/data.ts
https://app.clickup.com/t/86a5595tp
> CHORE: Change terms of use

- src/modules/transactions/components/TransactionCard/transfer-details/TransactionBreakdown.tsx
https://app.clickup.com/t/86a55d3fq
> FIX: Contract Call Card breakdown

- src/modules/auth/services/methods.ts
- src/modules/core/utils/assets/data.ts
- src/modules/network/hooks/useNetworks.ts
- Dets chain id dynamically from local storage
https://app.clickup.com/t/86a55baxt
> feat(assets): gets chain id from local storage

- src/layouts/dashboard/header.tsx
- src/modules/network/components/dialog/index.tsx
- src/modules/network/components/drawer/index.tsx
- src/modules/network/hooks/useNetworks.ts
- src/modules/network/services/methods.ts
https://app.clickup.com/t/86a54tc5n
> fix: network selection

- src/modules/core/hooks/useScreenSize.ts
- src/modules/termsOfUse/dialog/index.tsx
- src/modules/transactions/components/dialog/create/index.tsx
- src/modules/transactions/components/dialog/create/transactions.tsx
https://app.clickup.com/t/86a54z76a
this pr solves only the last topic of the task and is a complement to this PR: https://github.com/infinitybase/bako-safe-ui/pull/462
> CHORE: Fix create tx modal buttons to footer

- src/modules/termsOfUse/dialog/index.tsx
- src/modules/termsOfUse/utils/data.ts
https://app.clickup.com/t/86a55xa14
> FIX: Terms of use button is disable on android

- src/modules/auth/components/footer.tsx
https://app.clickup.com/t/86a5660zq
> CHORE: Add feedback button to sigin page

- src/modules/transactions/components/TransactionCard/TransactionStepper.tsx
https://app.clickup.com/t/86a52k8rq
this pr is a complement to this one: https://github.com/infinitybase/bako-safe-api/pull/275
> CHORE: Format date-fns to show 24h format on tx history

- src/modules/transactions/components/TransactionCard/CreationDate.tsx
- src/modules/transactions/components/TransactionCard/DetailsDialog.tsx
https://app.clickup.com/t/86a561cec
> CHORE: Increase characters limite in tx card on mobile version

- src/modules/transactions/hooks/context/useTransactionDetails.ts
https://app.clickup.com/t/86a566age
> fix(transaction): clear filters when changing page

- .env.example
- .env.preview
- .env.production
https://app.clickup.com/t/86a56p7gm
> FIX: Block explorer url

- src/modules/transactions/components/TransactionCard/transfer-details/mint-token/MintToken.tsx
- src/modules/transactions/hooks/details/useVerifyTransactionInformations.ts
https://app.clickup.com/t/86a56euc5
> FIX: Add validation to handle contract call with assets

- src/modules/vault/components/CardDetails.tsx
- src/modules/vault/hooks/assets/useVaultAssets.ts
https://app.clickup.com/t/86a56eyb1
> feat: add manual balance refetch and loader

- src/modules/transactions/components/TransactionCard/Status.tsx
- src/modules/transactions/hooks/signature/useSignTransaction.ts
https://app.clickup.com/t/86a4jgdax
> CHORE: Remove retry button from tx card

- src/modules/transactions/components/TransactionCard/Status.tsx
https://app.clickup.com/t/86a4jgdax
> FIX: Adjust tx card error badge

- src/modules/vault/components/box/index.tsx
- src/modules/workspace/hooks/details/useWorkspaceDetails.ts
- src/modules/workspace/hooks/useWorkspace.tsx
https://app.clickup.com/t/86a570qv7
> FIX: Signers can't access the vault

- src/modules/auth/components/signInWrapper.tsx
- src/modules/auth/components/webAuthn/form.tsx
- src/modules/auth/components/webAuthn/signIn.tsx
- src/modules/auth/hooks/signIn/useDappSignIn.ts
- src/modules/auth/hooks/signIn/useWebAuthnSignIn.ts
- src/modules/auth/pages/signin.tsx
- src/modules/dapp/pages/signIn.tsx
https://app.clickup.com/t/86a576zgx
> FIX: Disable webauthn input when create account request is laoding

- src/modules/core/utils/assets/data.ts
- src/modules/core/utils/types.ts
- src/modules/dapp/components/transaction/operation.tsx
- src/modules/transactions/components/TransactionCard/Amount.tsx
- src/modules/transactions/components/TransactionCard/Container.tsx
- src/modules/transactions/components/TransactionCard/DetailsDialog.tsx
- src/modules/transactions/components/TransactionCard/transfer-details/mint-token/MintToken.tsx
- src/modules/transactions/components/transactionCardMobile/index.tsx
- src/modules/transactions/hooks/details/useVerifyTransactionInformations.ts
- src/modules/transactions/hooks/index.ts
- src/modules/transactions/hooks/useFormatSummaryAssets.ts
- src/modules/transactions/hooks/useGetAssetsByOperations.ts
- src/utils/format-asset-amount.ts
- src/utils/index.ts
this pr depends on / complement: https://github.com/infinitybase/bako-safe-ui/pull/502
https://app.clickup.com/t/86a58cdtz
> FIX: Improve transaction operations validation

- src/modules/transactions/hooks/signature/useSignTransaction.ts
https://app.clickup.com/t/86a58pbdk
> CHORE: Disable sign button in tx card when users confirm the signature

- src/modules/vault/hooks/list/useVaultTransactionsList.ts
- src/modules/vault/pages/details/index.tsx
https://app.clickup.com/t/86a56wpje
> fix: infinite list on vaults transactions

- src/modules/transactions/hooks/create/useCreateTransactionForm.ts
- Adds specific validation and message to insufficient funds for the gas fee
https://app.clickup.com/t/86a5963v4
> Feat: add specific validation to insufficient funds for the gas fee

- .husky/commit-msg
- .husky/pre-commit
- src/modules/network/hooks/useNetworks.ts
- src/modules/transactions/hooks/create/useCreateTransactionForm.ts
- src/modules/vault/hooks/create/useCreateVaultForm.ts
- src/modules/workspace/hooks/details/useWorkspaceDetails.ts
- src/modules/workspace/utils/index.ts
- src/modules/workspace/utils/provider.ts
https://app.clickup.com/t/86a58c5r2
> feat: validate if address can receive assets

- src/modules/transactions/components/TransactionCard/Amount.tsx
- src/modules/transactions/components/TransactionCard/Container.tsx
- src/modules/transactions/components/TransactionCard/DetailsDialog.tsx
- src/modules/transactions/components/TransactionCard/TransactionStepper.tsx
- src/modules/transactions/components/TransactionCard/transfer-details/mint-token/MintToken.tsx
- src/modules/transactions/components/transactionCardMobile/index.tsx
- src/modules/transactions/hooks/details/useVerifyTransactionInformations.ts
https://app.clickup.com/t/86a5930hp
this pr depends on: https://github.com/infinitybase/bako-safe-api/pull/295 that's in progress
> FIX: Don't show amount component when contract call sent assets to the vault

- src/modules/assets-tokens/hooks/useTxAmountToUSD.ts
- src/modules/home/hooks/useTokensUSDAmountRequest.ts
- src/modules/transactions/components/TransactionCard/Amount.tsx
- src/modules/transactions/components/TransactionCard/AssetBoxInfo.tsx
- src/modules/transactions/components/TransactionCard/deposit-details/DetailItem.tsx
https://app.clickup.com/t/86a54qt5m
Just the 
gonna be tested in preview link
> CHORE: Show "--" instead of 0 when token is unknown

- src/layouts/dashboard/header.tsx
- src/modules/assets-tokens/hooks/useTxAmountToUSD.ts
- src/modules/auth/components/footer.tsx
- src/modules/dapp/components/transaction/asset.tsx
- src/modules/transactions/components/TransactionCard/Amount.tsx
https://app.clickup.com/t/86a596dwq
> FIX: USD Amount on tx card and send feedback msg

- src/modules/vault/hooks/list/useVaultTransactionsList.ts
- src/modules/vault/pages/details/index.tsx
https://app.clickup.com/t/86a59nr6r
gonna be tested
> FIX: Duplicated transaction card in vault list when selected by notification

- src/modules/vault/components/modal/hook.ts
- src/modules/workspace/hooks/details/useWorkspaceDetails.ts
- src/modules/workspace/hooks/useWorkspace.tsx
https://app.clickup.com/t/86a5bwmmq
> CHORE: Remove gif animation from vaults (selecting by the vault card in home and on vault modal in the vault itself)

- src/modules/transactions/components/dialog/create/form.tsx
- src/modules/transactions/components/dialog/create/index.tsx
- src/modules/transactions/hooks/create/useCreateTransaction.ts
- src/modules/transactions/hooks/create/useCreateTransactionForm.ts
- src/modules/transactions/utils.ts
- src/modules/vault/components/dialog/create/form/steps/success.tsx
https://app.clickup.com/t/86a4vqnju
the deposit logic was adjusted in the api: https://github.com/infinitybase/bako-safe-api/pull/309
gonna be tested
> CHORE: TX name field ins't required anymore and add a default tx name generator

- src/components/autocomplete/badge.tsx
https://app.clickup.com/t/86a55aaug
> FIX: Webauthn login input account options

- package.json
- src/components/bakoLoading/index.tsx
- src/components/dialog/modal.tsx
- src/layouts/dapp/container.tsx
- src/layouts/dashboard/container.tsx
- src/layouts/dashboard/content.tsx
- src/layouts/dashboard/drawer.tsx
- src/modules/auth/components/container.tsx
- src/modules/cli/components/APIToken/list/list.tsx
- src/modules/core/hooks/bakosafe/createVault.ts
- src/modules/core/hooks/bakosafe/vault.ts
- src/modules/dapp/pages/VaultConnector.tsx
- src/modules/home/pages/home.tsx
- src/modules/termsOfUse/dialog/index.tsx
- src/modules/vault/components/dialog/create/form/steps/addresses.tsx
- src/modules/vault/components/dialog/create/index.tsx
- src/modules/vault/components/modal/hook.ts
- src/modules/vault/components/modal/index.tsx
- src/modules/vault/hooks/create/useCreateVault.ts
- src/modules/vault/hooks/create/useCreateVaultDialog.ts
- src/modules/vault/layout/sidebar.tsx
> Vault improvements 

- src/modules/auth/components/signInWrapper.tsx
remove network selection from connector
> feat(connector): remove network selection from connector

- src/modules/auth/hooks/signIn/useWalletSignIn.ts
> fix(connector): fix connector conection

- src/modules/dapp/pages/switchNetwork.tsx
Adjusted footer on smaller screens and larger zoom
> adjusted footer on smaller screens and larger zoom

- src/config/socket.tsx
Adjusted socket client to wait until it has ID to connect correctly
Uploading Gravação de Tela 2025-04-25 às 23.05.02.mov…
> chore(network-soket-exchange-event): adjusted socket client connection

- src/components/autocomplete/basic.tsx
- src/modules/transactions/components/dialog/create/recipient/Form.tsx
> fix(transaction): create transaction addres fix on paste

- src/modules/transactions/components/dialog/create/recipient/Form.tsx
> fix(transaction): adjust create transaction address

- src/modules/assets-tokens/hooks/useAssetMap.ts
- src/modules/core/components/assetBalance/index.tsx
- src/modules/core/components/assetBalance/nfts-balance-card.tsx
- src/modules/core/utils/assets/types.ts
- src/modules/core/utils/formatter.ts
> feat(asset): enhance asset metadata handling with IPFS formatting

- src/modules/core/components/assetBalance/nft-dialog.tsx
> fix(assets): prevent error on map attributes with by a string type

- src/modules/vault/hooks/liquid-stake/useDepositLiquidStake.ts
Optimize liquid stake operation
> feat(refresh txs): refresh transactions after user sign or decline the tx

- src/layouts/dashboard/index.tsx
- src/modules/transactions/components/TransactionCard/transfer-details/address-actions/options/add-to-address-book.tsx
- src/modules/vault/layout/VaultDashBoard.tsx
Fix render dialog add address book when has many transactions
> fix(dialog render): change to use a new dialog add address book by every item

- src/modules/transactions/components/TransactionCard/AssetsIcon.tsx
- src/modules/vault/components/CardDetails.tsx
- src/modules/vault/components/TooltipPendingTx.tsx
- src/modules/vault/components/box/index.tsx
- src/modules/vault/components/liquid-stake/CardLiquidStake.tsx
improve vault ui when has pending tx
> Vs/feat/improve UI with pending tx

- src/components/select/asset.tsx
Fix dropdown getting away from select when scroll or zoom
> fix(dropdown move): making dropdown fixed with select input when scroll or zoom
